Fix ignore
dldl/sphinx-server pull request #25
Opened 2017-01-27 14:08 UTC by PLoic

@quentinus95 Can you review and test on your side please ? :)

2017-01-28 16:43 UTC, quentinus95 requested changes

2017-01-28 16:43 UTC, quentinus95 commented on .sphinx-server.yml
> -autobuild: false
autobuild should be disabled by default, please revert this change

2017-01-28 16:43 UTC, quentinus95 commented on server.py
> +        for ig in configuration.get('ignore'):
rename the var to `path` instead of `ig`

2017-01-28 16:43 UTC, quentinus95 commented on .sphinx-server.yml
> +#If you want to use a regex instead of provide name
missing space after #

2017-01-28 16:43 UTC, quentinus95 commented on .sphinx-server.yml
> +#If you want to use a regex instead of provide name
Change comment to: `You can also use regex to ignore specific type of files and folders.`

2017-01-28 16:43 UTC, quentinus95 commented on server.py
> +                                                 args=['-b', 'html', source_folder, build_folder])
remove the line break

2017-01-28 16:44 UTC, quentinus95 commented
You need to update the Readme too.

2017-02-03 09:24 UTC, quentinus95 commented
ping @PLoic

2017-02-03 09:42 UTC, PLoic commented
Done @quentinus95 :)

2017-02-03 10:33 UTC, quentinus95 commented
Container is crashing with the following `.sphinx-server.yml` file :

```yml

 autobuild: true
 
 ignore:
   - .git/
   - nope
   - lol/
 
 ignore_regex:
   - "*.tmp"
   - "lol*"
 
```

2017-02-03 10:53 UTC, PLoic commented
@quentinus95 Do you have some logs ?

2017-02-03 11:30 UTC, quentinus95 commented
```
Traceback (most recent call last):
  File "/opt/sphinx-server/server.py", line 83, in <module>
    regex_ignored=configuration.get('ignore_regex')
  File "/usr/lib/python2.7/site-packages/sphinx_autobuild/__init__.py", line 137, in __init__
    self._regex_ignored = [re.compile(r) for r in regex_ignored or []]
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat
```

2017-02-08 13:07 UTC, quentinus95 commented
up !

BTW, I'm currenty using the following configuration in a project:

```yml
ignore:
  - .git/
  - .idea/
  - _build/
  - "*.pyc"
```

and it *seems* to be working, I can investigate more if you want.

2017-02-08 13:20 UTC, PLoic commented
@quentinus95 Sorry for the time, I remove the support of the Regex for the time, but your first regex not looks like valid (http://stackoverflow.com/a/31386623)

2017-02-08 16:53 UTC, quentinus95 approved these changes

2017-02-08 16:53 UTC, quentinus95 commented
:+1: looks good for me

2017-02-08 16:54 UTC, merged